import type { Metadata } from 'next';
import localFont from 'next/font/local';

import './globals.css';

const suit = localFont({
  src: [
    { path: '../assets/fonts/SUIT-Regular.woff2', weight: '400' },
    { path: '../assets/fonts/SUIT-Bold.woff2', weight: '700' },
    { path: '../assets/fonts/SUIT-ExtraBold.woff2', weight: '800' },
  ],
  variable: '--font-suit',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html lang="en" className={`${suit.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <div className="bg-red-500 p-4 text-white md:bg-blue-500 lg:bg-green-500">
          브레이크포인트 테스트
        </div>
        <p className="text-12-extrabold">타이포그래피 테스트</p>
        {children}
      </body>
    </html>
  );
}
